version: '3.7'

services:
  redis:
    container_name: redis
    image: redis:5.0
    restart: always
    ports:
      - 6379:6379
    command: redis-server --requirepass 123456
    volumes:
      - redis_data:/data
    networks:
      - streamify-backend

  postgres:
    container_name: postgres
    image: postgres:latest
    restart: always
    ports:
      - 5433:5432
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - streamify-backend

volumes:
  redis_data:  # Added redis_data volume
  postgres_data:

networks:
  streamify-backend:
